### ISSUE TITLE
Can your please post a config sample?

### ISSUE THREAD

**Issue by psmith3** [luigifreitas/homebridge-http-thermostat#1]
I assume you are using the homebridge-http as the base. I am trying to build control for a Proliphix IP thermostat and I was able to control it like a light using homebridge-http and was even able to set the temp via the brightness command. I am trying to figure out the right settings for a thermostat. I basically want to set temperature, read temp and read humidity.

**Comment by eutampieri** [comment]
@TheHavocHero is right, you really should add some documentation or at leas a sample config.json snippet to let us figuring out how does this piece of code works.
It should be easy too because if you're using this service you must have added something to config.json.
Thanks in advance,
Eugenio

**Comment by rexy666** [comment]
I need config sample file too
